<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BDC6-DX-6BV6NK2" ignored="0" name="Test" tests="15" failures="6" timestamp="17 Sep 2019 10:06:55 GMT" time="0.145" errors="0">
  <testcase name="f" time="0.006" classname="day1.testng_demo"/>
  <testcase name="f1" time="0.002" classname="day1.testng_demo"/>
  <testcase name="f1" time="0.007" classname="day1.testng_demo3">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at day1.testng_demo3.f1(testng_demo3.java:9)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- f1 -->
  <testcase name="f2" time="0.002" classname="day1.testng_demo3"/>
  <testcase name="f3" time="0.001" classname="day1.testng_demo3"/>
  <testcase name="f4" time="0.001" classname="day1.testng_demo3">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at day1.testng_demo3.f4(testng_demo3.java:21)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- f4 -->
  <testcase name="f5" time="0.002" classname="day1.testng_demo3">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at day1.testng_demo3.f5(testng_demo3.java:25)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- f5 -->
  <testcase name="f6" time="0.002" classname="day1.testng_demo3"/>
  <testcase name="f7" time="0.002" classname="day1.testng_demo3"/>
  <testcase name="f8" time="0.001" classname="day1.testng_demo3">
    <failure type="java.lang.AssertionError" message="expected [null] but found [java.lang.Object@75842146]">
      <![CDATA[java.lang.AssertionError: expected [null] but found [java.lang.Object@75842146]
at day1.testng_demo3.f8(testng_demo3.java:39)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- f8 -->
  <testcase name="login" time="0.002" classname="day1.testng_demo2"/>
  <testcase name="logout" time="0.002" classname="day1.testng_demo2"/>
  <testcase name="f1" time="0.006" classname="day1.testngAssertions_demo1">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [12] but found [11]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [12] but found [11]
at day1.testngAssertions_demo1.f1(testngAssertions_demo1.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- f1 -->
  <testcase name="f2" time="0.004" classname="day1.testngAssertions_demo1">
    <failure type="java.lang.AssertionError" message="expected [12] but found [11]">
      <![CDATA[java.lang.AssertionError: expected [12] but found [11]
at day1.testngAssertions_demo1.f2(testngAssertions_demo1.java:20)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- f2 -->
  <testcase name="homepage" time="0.004" classname="day1.testng_demo2"/>
</testsuite> <!-- Test -->
